name: deckweiss_lints
description: Official Deckweiss linting rules for Flutter.
version: 1.0.0
homepage: https://github.com/deckweiss-gmbh/deckweiss_lints
repository: https://github.com/deckweiss-gmbh/deckweiss_lints

environment:
  sdk: ">=2.17.0 <3.0.0"
